### ISSUE TITLE
Feature Request: Add notes on how to determine the resistor values, add 30dB values

### ISSUE THREAD

**Issue by DeflateAwning** [SA6JKK/2512-RF-attenuator#1]
I want to use this on an RF project that requires a 30 dB attenuator. This seems like an awesome learning opportunity. Would you be willing to share how you determined the values to use for resistors? Thanks!

**Comment by SA6JKK** [comment]
I updated the readme with a link to the calculator I used and some design considerations. Good luck with the 30 dB attenuator :)
