### ISSUE TITLE
Request: Add a note about the production stackup for impedance control

### ISSUE THREAD

**Issue by DeflateAwning** [SA6JKK/2512-RF-attenuator#2]
Should this board be made on a 1.6mm FR4 board? Is it only 4 layers for proper impedance control? Or does it use a different stackup? This info would be great in the README. Thanks!

**Comment by SA6JKK** [comment]
I updated the readme with PCB and stackup information

**Comment by DeflateAwning** [comment]
Awesome, thank you!
